### ISSUE TITLE
Directory error?

### ISSUE THREAD

**Issue by GEMcConnochie** [wangsen1312/unsupervised3dhuman#10]
I am trying to install and run the demo and get the following error. Unable to open file (unable to open file: name = '/home/xinxin/code/data/SMPLmodel/neutral_smpl_mean_params.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

neutral_smpl_mean_params.h5 is located in C:\fit3d\smpl_models - does the directory need to change somewhere in the code?
![image](https://user-images.githubusercontent.com/89376037/213318575-afd5c0fe-361c-47e3-a9c9-7c6f38d4d48b.png)

**Comment by wangsen1312** [comment]
@GraceEMc Yes, you should change the  smpl_mean_file path in the Network.py.

**Comment by GEMcConnochie** [comment]
@wangsen1312 Thank you, that fixed that issue. However, I have encountered a new error with pickle as below. 
![image](https://user-images.githubusercontent.com/89376037/213328524-279988d5-8f3c-4db0-b620-87a7c5f48d99.png)

**Comment by wangsen1312** [comment]
@GraceEMc Please make sure you load the correct file path.

**Comment by milkshilin** [comment]
hello ,thank you for you great jobs,
i have a question when i ran your apps.



Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/')
Traceback (most recent call last):
  File "generate_pt.py", line 51, in <module>
    smplmodel = smplx.create(opt.smplmodel_folder, model_type="smpl",
  File "/usr/local/lib/python3.8/dist-packages/smplx/body_models.py", line 2400, in create
    return SMPL(model_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smplx/body_models.py", line 133, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path ./smpl_models/smpl/SMPL_FEMALE.pkl does not exist!

**Comment by milkshilin** [comment]
hallo，I am trying to install and run the demo and get the following error. 
`Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/')
00010805
Traceback (most recent call last):
  File "generate_pt.py", line 103, in <module>
    new_opt_cam_t = pointcloudEM(
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 161, in __call__
    body_optimizer.step(closure)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lbfgs.py", line 312, in step
    orig_loss = closure()
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 144, in closure
    loss =  body_fitting_loss_em(body_pose, preserve_pose, betas, preserve_betas, 
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 64, in body_fitting_loss_em
    point2mesh_loss = (point2mesh_weight**2) * get_point2mesh_loss(meshVerts, smpl_output, 1, modelfaces)
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 92, in get_point2mesh_loss
    point2mesh_loss, _ = point_mesh_face_distance_sep(meshes, pcls)
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1301, in point_mesh_face_distance_sep
    point_to_face = point_face_distance(
  File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1020, in forward
    dists, idxs = _C.point_face_dist_forward(
TypeError: point_face_dist_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: float) -> Tuple[at::Tensor, at::Tensor]

Invoked with: tensor([[ 0.0729,  0.2467,  0.2733],
        [-0.6035, -0.8212, -0.5948],
        [ 0.5932, -0.8468, -0.2534],
        ...,
        [-0.1043, -0.0415,  0.1677],
        [ 0.1239, -0.0707, -0.0962],
        [-0.1576, -0.1194,  0.0764]], device='cuda:0'), tensor([0], device='cuda:0'), tensor([[[0.2953, 0.6221, 0.0862],
         [0.2887, 0.6216, 0.0735],
         [0.2901, 0.6374, 0.0834]],

        [[0.2901, 0.6374, 0.0834],
         [0.2887, 0.6216, 0.0735],
         [0.2811, 0.6334, 0.0691]],

        [[0.2887, 0.6216, 0.0735],
         [0.2953, 0.6221, 0.0862],
         [0.2938, 0.6116, 0.0754]],

        ...,

        [[0.1621, 0.0994, 0.0552],
         [0.1744, 0.1200, 0.0353],
         [0.1675, 0.1207, 0.0566]],

        [[0.1744, 0.1200, 0.0353],
         [0.1785, 0.1414, 0.0357],
         [0.1675, 0.1207, 0.0566]],

        [[0.1675, 0.1207, 0.0566],
         [0.1785, 0.1414, 0.0357],
         [0.1723, 0.1426, 0.0573]]], device='cuda:0', grad_fn=<IndexBackward0>), tensor([0], device='cuda:0'), 2048`

**Comment by aakritiadhikari** [comment]
> hallo，I am trying to install and run the demo and get the following error. `Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/') 00010805 Traceback (most recent call last): File "generate_pt.py", line 103, in new_opt_cam_t = pointcloudEM( File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 161, in **call** body_optimizer.step(closure) File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 140, in wrapper out = func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/torch/optim/lbfgs.py", line 312, in step orig_loss = closure() File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 144, in closure loss = body_fitting_loss_em(body_pose, preserve_pose, betas, preserve_betas, File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 64, in body_fitting_loss_em point2mesh_loss = (point2mesh_weight**2) * get_point2mesh_loss(meshVerts, smpl_output, 1, modelfaces) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 92, in get_point2mesh_loss point2mesh_loss, _ = point_mesh_face_distance_sep(meshes, pcls) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1301, in point_mesh_face_distance_sep point_to_face = point_face_distance( File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1020, in forward dists, idxs = _C.point_face_dist_forward( TypeError: point_face_dist_forward(): incompatible function arguments. The following argument types are supported: 1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: float) -> Tuple[at::Tensor, at::Tensor]
> 
> Invoked with: tensor([[ 0.0729, 0.2467, 0.2733], [-0.6035, -0.8212, -0.5948], [ 0.5932, -0.8468, -0.2534], ..., [-0.1043, -0.0415, 0.1677], [ 0.1239, -0.0707, -0.0962], [-0.1576, -0.1194, 0.0764]], device='cuda:0'), tensor([0], device='cuda:0'), tensor([[[0.2953, 0.6221, 0.0862], [0.2887, 0.6216, 0.0735], [0.2901, 0.6374, 0.0834]],
> 
> ```
>     [[0.2901, 0.6374, 0.0834],
>      [0.2887, 0.6216, 0.0735],
>      [0.2811, 0.6334, 0.0691]],
> 
>     [[0.2887, 0.6216, 0.0735],
>      [0.2953, 0.6221, 0.0862],
>      [0.2938, 0.6116, 0.0754]],
> 
>     ...,
> 
>     [[0.1621, 0.0994, 0.0552],
>      [0.1744, 0.1200, 0.0353],
>      [0.1675, 0.1207, 0.0566]],
> 
>     [[0.1744, 0.1200, 0.0353],
>      [0.1785, 0.1414, 0.0357],
>      [0.1675, 0.1207, 0.0566]],
> 
>     [[0.1675, 0.1207, 0.0566],
>      [0.1785, 0.1414, 0.0357],
>      [0.1723, 0.1426, 0.0573]]], device='cuda:0', grad_fn=<IndexBackward0>), tensor([0], device='cuda:0'), 2048`
> ```

Hi, 
I also got the same error.

**Comment by wangsen1312** [comment]
@aakritiadhikari Seems due to the function's compability. Can you share the pytroch3d version of your environment?

**Comment by milkshilin** [comment]
> > hallo，I am trying to install and run the demo and get the following error. `Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/') 00010805 Traceback (most recent call last): File "generate_pt.py", line 103, in new_opt_cam_t = pointcloudEM( File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 161, in **call** body_optimizer.step(closure) File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 140, in wrapper out = func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/torch/optim/lbfgs.py", line 312, in step orig_loss = closure() File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/surfaceem.py", line 144, in closure loss = body_fitting_loss_em(body_pose, preserve_pose, betas, preserve_betas, File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 64, in body_fitting_loss_em point2mesh_loss = (point2mesh_weight**2) * get_point2mesh_loss(meshVerts, smpl_output, 1, modelfaces) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/customloss.py", line 92, in get_point2mesh_loss point2mesh_loss, _ = point_mesh_face_distance_sep(meshes, pcls) File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1301, in point_mesh_face_distance_sep point_to_face = point_face_distance( File "/content/drive/MyDrive/unsupervised3dhuman-main/src/utils.py", line 1020, in forward dists, idxs = _C.point_face_dist_forward( TypeError: point_face_dist_forward(): incompatible function arguments. The following argument types are supported: 1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: float) -> Tuple[at::Tensor, at::Tensor]
> > Invoked with: tensor([[ 0.0729, 0.2467, 0.2733], [-0.6035, -0.8212, -0.5948], [ 0.5932, -0.8468, -0.2534], ..., [-0.1043, -0.0415, 0.1677], [ 0.1239, -0.0707, -0.0962], [-0.1576, -0.1194, 0.0764]], device='cuda:0'), tensor([0], device='cuda:0'), tensor([[[0.2953, 0.6221, 0.0862], [0.2887, 0.6216, 0.0735], [0.2901, 0.6374, 0.0834]],
> > ```
> >     [[0.2901, 0.6374, 0.0834],
> >      [0.2887, 0.6216, 0.0735],
> >      [0.2811, 0.6334, 0.0691]],
> > 
> >     [[0.2887, 0.6216, 0.0735],
> >      [0.2953, 0.6221, 0.0862],
> >      [0.2938, 0.6116, 0.0754]],
> > 
> >     ...,
> > 
> >     [[0.1621, 0.0994, 0.0552],
> >      [0.1744, 0.1200, 0.0353],
> >      [0.1675, 0.1207, 0.0566]],
> > 
> >     [[0.1744, 0.1200, 0.0353],
> >      [0.1785, 0.1414, 0.0357],
> >      [0.1675, 0.1207, 0.0566]],
> > 
> >     [[0.1675, 0.1207, 0.0566],
> >      [0.1785, 0.1414, 0.0357],
> >      [0.1723, 0.1426, 0.0573]]], device='cuda:0', grad_fn=<IndexBackward0>), tensor([0], device='cuda:0'), 2048`
> > ```
> 
> Hi, I also got the same error.

You need set up a default triangel Area value in pytorch3d.

**Comment by aakritiadhikari** [comment]
my error looks like this on point_arr2 line 145: 
(fit3d) aakriti@aakriti-HP-Z840-Workstation:~/unsupervised3dhuman$ python generate_pt.py --filename ./demo/demo_pt/00010805.ply --gender female
10000000000
Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/')
WARNING: You are using a SMPL model, with only 10 shape coefficients.
00010805
Traceback (most recent call last):
  File "generate_pt.py", line 145, in <module>
    point_arr2
  File "/home/aakriti/unsupervised3dhuman/src/surfaceem.py", line 160, in __call__
    body_optimizer.step(closure)
  File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/optim/lbfgs.py", line 311, in step
    orig_loss = closure()
  File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/aakriti/unsupervised3dhuman/src/surfaceem.py", line 155, in closure
    search_tree=search_tree, pen_distance=pen_distance, filter_faces=filter_faces)
  File "/home/aakriti/unsupervised3dhuman/src/customloss.py", line 67, in body_fitting_loss_em
    point2mesh_loss = (point2mesh_weight**2) * get_point2mesh_loss(meshVerts, smpl_output, 1, modelfaces)
  File "/home/aakriti/unsupervised3dhuman/src/customloss.py", line 95, in get_point2mesh_loss
    point2mesh_loss, _ = point_mesh_face_distance_sep(meshes, pcls)
  File "/home/aakriti/unsupervised3dhuman/src/utils.py", line 1302, in point_mesh_face_distance_sep
    points, points_first_idx, tris, tris_first_idx, max_points
  File "/home/aakriti/unsupervised3dhuman/src/utils.py", line 1021, in forward
    points, points_first_idx, tris, tris_first_idx, max_points
TypeError: point_face_dist_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: float) -> Tuple[at::Tensor, at::Tensor]

Invoked with: tensor([[-0.0942, -0.3133,  0.0266],
        [ 0.2000,  1.0667, -0.1965],
        [ 0.5582, -0.8512, -0.6090],
        ...,
        [ 0.0807, -0.2472, -0.1229],
        [ 0.1618,  0.2637,  0.2742],
        [-0.1412,  0.1836,  0.0719]], device='cuda:0'), tensor([0], device='cuda:0'), tensor([[[0.2251, 0.6474, 0.0730],
         [0.2190, 0.6463, 0.0601],
         [0.2189, 0.6622, 0.0699]],

        [[0.2189, 0.6622, 0.0699],
         [0.2190, 0.6463, 0.0601],
         [0.2106, 0.6575, 0.0554]],

        [[0.2190, 0.6463, 0.0601],
         [0.2251, 0.6474, 0.0730],
         [0.2247, 0.6367, 0.0622]],

        ...,

        [[0.1505, 0.1147, 0.0535],
         [0.1619, 0.1363, 0.0339],
         [0.1536, 0.1369, 0.0548]],

        [[0.1619, 0.1363, 0.0339],
         [0.1638, 0.1584, 0.0342],
         [0.1536, 0.1369, 0.0548]],

        [[0.1536, 0.1369, 0.0548],
         [0.1638, 0.1584, 0.0342],
         [0.1559, 0.1596, 0.0554]]], device='cuda:0', grad_fn=<IndexBackward>), tensor([0], device='cuda:0'), 2048


My pytorch3d is pytorch3d                     0.7.2. It is compatible to my system and already loaded the model. I can see output for other variables except new_opt_cam_t.. How to set up default triangel area value in pytorch3d?

**Comment by milkshilin** [comment]
> my error looks like this on point_arr2 line 145: (fit3d) aakriti@aakriti-HP-Z840-Workstation:~/unsupervised3dhuman$ python generate_pt.py --filename ./demo/demo_pt/00010805.ply --gender female 10000000000 Namespace(SMPL_downsample='./smpl_models/SMPL_downsample_index.pkl', batchSize=1, dirs_save='./demo/demo_pt_save/', filename='./demo/demo_pt/00010805.ply', gender='female', gpu_ids=0, num_iters=20, restore_path='./pretrained/model_best_pt.pth', smplmodel_folder='./smpl_models/') WARNING: You are using a SMPL model, with only 10 shape coefficients. 00010805 Traceback (most recent call last): File "generate_pt.py", line 145, in point_arr2 File "/home/aakriti/unsupervised3dhuman/src/surfaceem.py", line 160, in **call** body_optimizer.step(closure) File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context return func(*args, **kwargs) File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/optim/lbfgs.py", line 311, in step orig_loss = closure() File "/home/aakriti/anaconda3/envs/fit3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context return func(*args, **kwargs) File "/home/aakriti/unsupervised3dhuman/src/surfaceem.py", line 155, in closure search_tree=search_tree, pen_distance=pen_distance, filter_faces=filter_faces) File "/home/aakriti/unsupervised3dhuman/src/customloss.py", line 67, in body_fitting_loss_em point2mesh_loss = (point2mesh_weight**2) * get_point2mesh_loss(meshVerts, smpl_output, 1, modelfaces) File "/home/aakriti/unsupervised3dhuman/src/customloss.py", line 95, in get_point2mesh_loss point2mesh_loss, _ = point_mesh_face_distance_sep(meshes, pcls) File "/home/aakriti/unsupervised3dhuman/src/utils.py", line 1302, in point_mesh_face_distance_sep points, points_first_idx, tris, tris_first_idx, max_points File "/home/aakriti/unsupervised3dhuman/src/utils.py", line 1021, in forward points, points_first_idx, tris, tris_first_idx, max_points TypeError: point_face_dist_forward(): incompatible function arguments. The following argument types are supported: 1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: float) -> Tuple[at::Tensor, at::Tensor]
> 
> Invoked with: tensor([[-0.0942, -0.3133, 0.0266], [ 0.2000, 1.0667, -0.1965], [ 0.5582, -0.8512, -0.6090], ..., [ 0.0807, -0.2472, -0.1229], [ 0.1618, 0.2637, 0.2742], [-0.1412, 0.1836, 0.0719]], device='cuda:0'), tensor([0], device='cuda:0'), tensor([[[0.2251, 0.6474, 0.0730], [0.2190, 0.6463, 0.0601], [0.2189, 0.6622, 0.0699]],
> 
> ```
>     [[0.2189, 0.6622, 0.0699],
>      [0.2190, 0.6463, 0.0601],
>      [0.2106, 0.6575, 0.0554]],
> 
>     [[0.2190, 0.6463, 0.0601],
>      [0.2251, 0.6474, 0.0730],
>      [0.2247, 0.6367, 0.0622]],
> 
>     ...
> 
>     [[0.1505, 0.1147, 0.0535],
>      [0.1619, 0.1363, 0.0339],
>      [0.1536, 0.1369, 0.0548]],
> 
>     [[0.1619, 0.1363, 0.0339],
>      [0.1638, 0.1584, 0.0342],
>      [0.1536, 0.1369, 0.0548]],
> 
>     [[0.1536, 0.1369, 0.0548],
>      [0.1638, 0.1584, 0.0342],
>      [0.1559, 0.1596, 0.0554]]], device='cuda:0', grad_fn=<IndexBackward>), tensor([0], device='cuda:0'), 2048
> ```
> 
> My pytorch3d is pytorch3d 0.7.2. It is compatible to my system and already loaded the model. I can see output for other variables except new_opt_cam_t.. How to set up default triangel area value in pytorch3d?

class _PointFaceDistance(Function):
    """
    Torch autograd Function wrapper PointFaceDistance Cuda implementation
    """

    @staticmethod
    def forward(
        ctx,
        points,
        points_first_idx,
        tris,
        tris_first_idx,
        max_points,
        min_triangle_area=0.00001,
    ):
scr/utils/lines around 1000,you could find it by yourself

**Comment by aakritiadhikari** [comment]
didn't fix the issue. Do you also do for _FacePointDistance. 
But then, also didn't fix the issue.

**Comment by aakritiadhikari** [comment]
I followed from this: https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/loss/point_mesh_distance.html
but, then I get an error for loss. backward() in src/surfaceem.py for point_arr2.

**Comment by aakritiadhikari** [comment]
I updated _PointFaceDistance and _FacePointDistance from here : https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/loss/point_mesh_distance.html 
Then, it worked. 

Thanks.

**Comment by wangsen1312** [comment]
@aakritiadhikari It's good to know you already solved it! Thanks to your useful discussion
