### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by Passion-ysh** [wangsen1312/unsupervised3dhuman#5]
作者你好，请问下后续会发布训练代码吗？

**Comment by wangsen1312** [comment]
@Passion-ysh 您好 不好意思 我们的文章还没有中~ 我们会在中了以后再放训练代码~

**Comment by Passion-ysh** [comment]
> 

好滴，期待训练代码。

**Comment by pramishp** [comment]
Thank you very much for open sourcing the code. I would also like to request the training code if your article is in.
