### ISSUE TITLE
How to convert depth image to ply file

### ISSUE THREAD

**Issue by LinyeLi60** [wangsen1312/unsupervised3dhuman#7]
Hi, Wang sen, I am not very familiar with point cloud processing, I don't know how to convert **depth** image with camera intrinsic parameters to **ply** file, could you help me, thank you.

**Comment by wangsen1312** [comment]
This blog is very interesting. It should help.  https://medium.com/yodayoda/from-depth-map-to-point-cloud-7473721d3f

If you still don not know how to convert, you can send one sample depth here. I may help you on this.
