### ISSUE TITLE
Depth demo

### ISSUE THREAD

**Issue by DavidBoja** [wangsen1312/unsupervised3dhuman#9]
Hi,

I ran the demo you provdied for fitting the SMPL model onto a partial scan:

`python generate_depth.py --filename ./demo/demo_depth/shortshort_flying_eagle.000075_depth.ply --gender male
`

but the `surface_EM_depth` minimization outpus `NaN` s for the demo example you provided. Does the code work for you?

Thanks in advance,
David

**Comment by DavidBoja** [comment]
Even though there is a known issue for LBFGS giving NaNs (https://github.com/pytorch/pytorch/issues/5953), I think the  issue here results from the smpl model which cannot handle the "crazy" inputs given by LBFGS.
That is at least where the first NaNs start appearing when running the `surface_EM_depth` optimization step.

Did you have the same issues when evaluating on the CAPE / CMU / FAUST datasets?

**Comment by wangsen1312** [comment]
@DavidBoja Actually I met the same problem before.  From my understanding, two things may trigger this issue.
1. the first step's result is so bad, the optimize function can not work very well.
2. LBFGS lr can trigger this, when you change it smaller, the NaNs things will disappear. However, the small lr may not get very good results sometimes.

In my evaluation, if I met the problem, I will log it and use other set of optimize parameters to run it again.
